version: "3.7"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: nodeapp
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  node:
    build:
      dockerfile: ./Dockerfile
      context: .
    container_name: node
    depends_on:
      - postgres
    restart: always
    ports:
      - "4000:4000"
